api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file

providers:
  docker:
    exposedByDefault: false
    network: proxy
    watch: true

  file:
    filename: /configurations/dynamic.yml